# Dependencies
markdown:         redcarpet
highlighter: pygments

# Permalinks
permalink:        pretty

# Setup
title:            Samael
tagline:          ''
description:      '
douban: <a href="http://www.douban.com/people/keep.moving/" target="_blank">samael</a><br>
email: <a href="mailto:samael.65535@gamil.com" target="_blank">samael</a><br>
twitter: <a href="https://twitter.com/samael65535" target="_blank">@samael65535</a><br>
weibo: <a href="http://weibo.com/1871138727" target="_blank">@samael65535</a><br>
'
url:              http://samael.cn
author:
  name : samael
  email : samael.65535@gmail.com
  github : samael65535
  twitter : samael65535
  feedburner : feedname


gems: [jekyll-paginate]
paginate:         2

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/samael65535/samael65535.github.com

production_url : http://samael65535.github.com


# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
    tracking_id : 'UA-57926253-1'
  getclicky :
    site_id :
  mixpanel :
    token : '_MIXPANEL_TOKEN_'
